### ISSUE TITLE
Support for concurrency

### ISSUE THREAD

**Issue by PiotrPrzybylak** [cpapidas/Golang-Translator#2]
Hi. If you keep current language in global variable doesn't that mean every request overrides it with its own value? This way you can get response in language set by some other user if he happens to be using the app at the same time. Or am I missing something?

**Comment by cpapidas** [comment]
It's up to you how to configure and use the lib, I have created the main logic. If you use Non-Blocking servers then yes it's should be a problem but you can solve it easily with OOP.
